sudo: required
dist: trusty
language: shell
services:
- docker
env:
  matrix:
  - STACK=cedar-14 IMAGE_TAG=heroku/cedar:14 PRIVATE_IMAGE_TAG=heroku/cedar-private:14
  - STACK=heroku-16 IMAGE_TAG=heroku/heroku:16 PRIVATE_IMAGE_TAG=heroku/heroku-private:16
  - STACK=heroku-18 IMAGE_TAG=heroku/heroku:18 PRIVATE_IMAGE_TAG=heroku/heroku-private:18
  global:
  - secure: qsOv8gjVqCeV7kqx8FntMKD51EZCO2j7oTY8fWwqgndRCT5kHtcJA0vGMW0rjGDlDMuEB5wyUc2RT9ZWMslyKWxgS4Su5zSdAlE8D6TXXpHDU1ZPmOA+cnNm4TIMIrcUlGeCWcK4NNe8Vg7VvrTstooLB/ZjgaCKylkxs7zWq2g=
  - secure: G3A9OqzMggD1DGWivgvo34FS6MeKwOqgzBDa367Gp/xb0ilKrh+sLGwPWOllKtUcgf/itznrsLJre4svj9OUII7X5OdqrMByquCMBX+xck8CiqZQWkNh9FfmTRd7QJtGySdh+tD0Vqjuz1b1wH3YqM+DC740a4veZeW6pDBz9S4=
  - secure: qTImKa1qsHdMmreZHEOU1JgY2adQ5E/ZHIJw3Nvm5tDqz5lbG5dUahIj1JvzP+FdIoEo6R+0t8C8xD9mBwnz4nMmnahQMnYzYltC9bO9kA7cSI/dktAjQKSBLwtDacFB6jT0UVf7lE7Cxxy70q8L5lkvbqgCxDvU7C16TinYgKA=
script:
- bin/build.sh $STACK $IMAGE_TAG $IMAGE_TAG-build
- |
  status="$(git status --porcelain)"
  if [[ -n "$status" ]]; then
    echo -e "Regenerated files differ from checked-in versions!\n${status}\n"
    git diff --exit-code
  fi
deploy:
  - provider: script
    script: bin/convert-and-publish-to-heroku.sh
    on:
      tags: true
  - provider: script
    script: sh bin/publish-to-dockerhub.sh
    on:
      all_branches: true
