sudo: required
dist: trusty
language: shell
services:
- docker
branches:
  # /!\ Every build will always trigger a deploy
  only:
  - master
  - /^v\d+(\.\d+)?(\.\d+)?(-\S*)?$/
env:
  matrix:
  - STACK=cedar-14 IMAGE_TAG=heroku/cedar:14
  - STACK=heroku-16 IMAGE_TAG=heroku/heroku:16
  - STACK=heroku-18 IMAGE_TAG=heroku/heroku:18
  global:
  - secure: qsOv8gjVqCeV7kqx8FntMKD51EZCO2j7oTY8fWwqgndRCT5kHtcJA0vGMW0rjGDlDMuEB5wyUc2RT9ZWMslyKWxgS4Su5zSdAlE8D6TXXpHDU1ZPmOA+cnNm4TIMIrcUlGeCWcK4NNe8Vg7VvrTstooLB/ZjgaCKylkxs7zWq2g= # DOCKER_HUB_USERNAME
  - secure: Dlf4eHJVTQ1bCZuLaaNoKjUmS8SL7Jn2BZCdP7UHZhte+RKchCjajhoObT/fAZ3c5EFfV2pd8NKkWPW0REwN/lodgRPeslYiyNaiIRCVoKRGASxHXHO17wwkMNor2Bi7u6InL3WC1t5YbY2abVaeavtz1lAyn1XTNysc+/s1onw= # DOCKER_HUB_PASSWORD
script:
- "bin/build.sh $STACK $IMAGE_TAG $IMAGE_TAG-build"
- |
  status="$(git status --porcelain)"
  if [[ -n "$status" ]]; then
    echo -e "Regenerated files differ from checked-in versions!\n${status}\n"
    git diff --exit-code
  fi
deploy:
  provider: script
  script: sh bin/publish.sh
  on:
    all_branches: true
